apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ui
  labels:
    app: react-ui
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: tonytangcn/react-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80