apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: &app dotnet-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: *app
        image: tonytangcn/dotnet-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8080