apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ui
  labels:
    app: &app react-ui
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: *app
        image: tonytangcn/react-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80