apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-logic
  labels:
    app: &app go-logic
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: *app
        image: tonytangcn/go-logic
        imagePullPolicy: Always
        ports:
        - containerPort: 5000